services:
  backend:
    #build:
    #  context: ..  
    #  dockerfile: docker/Dockerfile
    image: ryze05/eventpass-server:4.0
    container_name: eventpass-back
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/eventpass
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user
    extra_hosts:
      - "host.docker.internal:host-gateway"